apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - name: ftps
      protocol: TCP
      port: 21
    - name: ftps-data
      protocol: TCP
      port: 10000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        # image: fauria/vsftpd
        image: ftps:vscabell
        imagePullPolicy: Never
        # command: [ "/bin/sh", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]
        ports:
          - name: ftps
            containerPort: 21
        ports:
          - name: ftps-data
            containerPort: 10000
        # volumeMounts:
        #   - mountPath: "/home/vsftpd"
        #     name: ftps-pv-storage
        # env:
        #   - name: FTP_USER
        #     value: "user"
        #   - name: FTP_PASS
        #     value: "pass1234"
# ---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: ftps-pv-volume
#   labels:
#     type: local
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/tmp/data"
# ---
#   kind: PersistentVolumeClaim
#   apiVersion: v1
#   metadata:
#     name: ftps-pv-claim
#   spec:
#     accessModes:
#       - ReadWriteOnce
#     resources:
#       requests:
#         storage: 1Gi