apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - name: ftps
      protocol: TCP
      port: 21
    - name: ftps-data
      protocol: TCP
      port: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      hostname: ftps
      containers:
      - name: ftps
        image: ftps:vscabell
        imagePullPolicy: Never
        ports:
          - name: ftps
            containerPort: 21
          - name: ftps-data
            containerPort: 30000
        volumeMounts:
          - name: ftps-persistent-storage
            mountPath: /home/admin
        livenessProbe:
          exec:
            command:
              - bin/sh
              - -c
              - ./liveness.sh
          periodSeconds: 15
          failureThreshold: 1
          initialDelaySeconds: 30
      volumes:
        - name: ftps-persistent-storage
          persistentVolumeClaim:
            claimName: ftps-pvc
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: ftps-pv
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#       storage: 1Gi
#   accessModes:
#       - ReadWriteOnce
#   hostPath:
#     path: "/mnt/ftps"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: ftps-pvc
spec:
    # storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi