apiVersion: v1
kind: Service
metadata:
  name: mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    # targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        # image: mysql:latest
        image: mysql:vscabell
        imagePullPolicy: Never
        ports:
          - containerPort: 3306
        envFrom:
          - configMapRef:
              name: mysql-configmap
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  MYSQL_ROOT_PASSWORD: "admin"
  MYSQL_DATABASE: "wordpress"
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "admin"
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-pv
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-pv-claim
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi