apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: phpmyadmin
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
    - name: phpmyadmin
      port: 5000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      hostname: phpmyadmin
      containers:
      - name: phpmyadmin
        image: phpmyadmin:vscabell
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: phpmyadmin
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - c
              - pgrep -f telegraf; pgrep -f php-fpm7; pgrep -f nginx
          periodSeconds: 10
          failureThreshold: 1
          initialDelaySeconds: 15