
# apiVersion: v1
# kind: Service
# metadata:
#   name: wordpress
#   annotations:
#     metallb.universe.tf/allow-shared-ip: shared
#   labels:
#     app: wordpress
# spec:
#   type: LoadBalancer
#   selector:
#     app: wordpress
#   ports:
#     - name: wordpress
#       port: 5050
#       protocol: TCP
#       targetPort: 80
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: wordpress
#   labels:
#     app: wordpress
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: wordpress
#   template:
#     metadata:
#       labels:
#         app: wordpress
#     spec:
#       containers:
#       - name: wordpress
#         image: wordpress:4.8-apache
#         # image: wordpress:vscabell
#         # imagePullPolicy: Never
#         command: [ "/bin/bash", "-c", "--" ]
#         args: [ "while true; do sleep 30; done;" ]
#         ports:
#         - containerPort: 5050
#           name: wordpress
#         envFrom:
#           - configMapRef:
#               name: wordpress-configmap
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: wordpress-configmap
# data:
#   DB_HOST: "mysql"
#   DB_USER: "admin"
#   DB_PASSWORD: "123456"
#   DB_NAME: "wordpress-db"



apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    component: wordpress
spec:
  selector:
    component: wordpress
  ports:
    - name: wp-port
      protocol: TCP
      port: 5050
      # targetPort: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    component: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      component: wordpress
  template:
    metadata:
      labels:
        component: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:vscabell
        ports:
        - containerPort: 5050
        imagePullPolicy: Never