apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - name: wordpress
      port: 5050
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      hostname: wordpress
      containers:
      - name: wordpress
        image: wordpress:vscabell
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: wordpress
        livenessProbe:
          exec:
            command:
              - bin/sh
              - -c
              - ./liveness.sh
          periodSeconds: 15
          failureThreshold: 2
          initialDelaySeconds: 80